export const meta = {
  name: 'kernel-articles',
  description: 'Write + verify all 70 remaining Kernel Engineering articles in the bearblog-worklog style',
  phases: [{ title: 'Write' }, { title: 'Verify' }],
}

const DIR = 'kernel-engineering-site'
const PRE = `You are writing ONE article for the Kernel Engineering knowledge site (a serious, beautiful GPU-kernel course by Vizuara AI Labs).

BEFORE WRITING, read these three files (they define the exact style and are non-negotiable):
- ${DIR}/STYLE.md  (canonical style spec — voice, figure grammar, sidenotes)
- ${DIR}/articles/the-three-regimes.md  (exemplar: a concept article)
- ${DIR}/articles/gemm-kernel-1-naive.md (exemplar: a worklog/kernel article)

Then WRITE the markdown file at the EXACT path given below. Rules:
- Output ONLY the article body markdown. Do NOT put the title as an H1 at the top (the site adds it). Start directly with a strong opening paragraph. Use ## for internal section headings (and ### sparingly).
- VOICE: first-person worklog, honest, incremental — exactly like the two exemplars. For kernel/optimization articles use the loop: hypothesis -> code (concept first, code after) -> profile/SASS evidence -> a BOLD number (% of cuBLAS or x speedup) -> bridge to the next step.
- Length 1200-2600 words. Substantive and technically correct — a hiring manager should respect it.
- Inline code in backticks (renders red): variables, intrinsics, sizes (threadIdx.x, float4, wgmma, 228 KiB). Bold key terms on first mention with expansion, e.g. **Streaming Multiprocessor** (SM).
- CODE BLOCKS: fenced with a language tag (cpp / python), realistic and concise. Not every article needs one; kernel articles do.
- FIGURES: include 3-5 using EXACTLY this syntax on their own line:
    [[fig: <a DETAILED hand-drawn Excalidraw scene description following STYLE.md Part C — name the boxes, the hatched matrices, the colored handwritten annotations (blue=mechanism, green=specs, red=dims/labels, purple=code, orange=emphasis), the dashed arrows, numbered circles, and the dashed takeaway box> || <one-line caption>]]
  The scene prompt must be specific enough to draw without seeing the article. Vary the archetypes (architecture map, tiling walkthrough, memory pyramid, SASS+diagram, pipeline timeline).
- SIDENOTES: include 2-5 using EXACTLY: [[sn: <the caveat / compiler internal / exact-number correction / "one exception" nuance>]] placed mid-sentence. These are the right-margin citations — use them for the kind of content that would interrupt the main flow.
- Cross-link to sibling articles with normal markdown links to <slug>.html (e.g. [the three regimes](the-three-regimes.html), [shared memory](shared-memory-l1.html)) where natural.
- Do NOT invent benchmark numbers wildly; use the hardware facts below and the given source. If unsure of an exact figure, describe the trend rather than fabricate a precise number.

HARDWARE FACTS (H100 SXM5, use these; do not contradict): 8 GPCs, ~132 SMs, 989 TFLOP/s BF16 tensor (realistic, no sparsity), 3.35 TB/s HBM3, 80 GB; L2 ~50 MiB (two partitions + crossbar, 128 B line / 4x32 B sectors); SMEM+L1 share 256 KiB per SM, up to 228 KiB usable as SMEM, 32 banks; register file 256 KB/SM (65536 x 32-bit), max 255 registers/thread; warp = 32 threads; max 1024 threads/block; DSMEM/thread-block clusters/TMA/WGMMA are new in Hopper (sm_90a); tcgen05, Tensor Memory (TMEM), CTA pairs, NVFP4 (e2m1 + FP8 block scales) are Blackwell (B200/GB300). GEMM ladder %-of-cuBLAS milestones: naive 1.3, coalescing 8.5, SMEM 12.8, 1D-tile 36.5, 2D-tile 68.7, vectorized 78.4, autotune 84.8, warptile 93.7.

Return ONLY: the slug, the word count, and the number of [[fig:]] and [[sn:]] you included. Do not paste the article back.`

function writePrompt(a) {
  return `${PRE}

WRITE THIS FILE: ${DIR}/articles/${a.slug}.md
ARTICLE TITLE (do not repeat as H1): "${a.title}"
SECTION: ${a.section}
WHAT IT MUST COVER: ${a.brief}
PRIMARY SOURCES (read/fetch if useful): ${a.src}`
}

function verifyPrompt(a) {
  return `Read ${DIR}/STYLE.md, then read the article file ${DIR}/articles/${a.slug}.md.
You are the technical + style editor. Check and FIX IN PLACE (using Edit) any of:
1) TECHNICAL ERRORS or hallucinated APIs/numbers (article: "${a.title}", section ${a.section}; must-cover: ${a.brief}). Cross-check against your knowledge and the sources: ${a.src}. Fix wrong claims; if a precise number is dubious, soften to a trend.
2) STYLE violations vs STYLE.md and the exemplars: must be first-person worklog voice; kernel articles must follow hypothesis->code->profile->bold-number->bridge; inline code in backticks; 3-5 [[fig:]] with DETAILED semantic-color Excalidraw prompts; 2-5 [[sn:]] sidenotes; no H1 title at top; internal ## headings.
3) Ensure figure prompts are specific and follow the color grammar (blue=mechanism, green=specs, red=dims/labels, purple=code, orange=emphasis, yellow=packaging/output). Improve any vague figure prompt.
Make the edits directly in the file. Return ONLY: slug, a one-word verdict (CLEAN or FIXED), and a terse list of what you changed (max 4 items).`
}

const S = {
  MODAL:'https://modal.com/gpu-glossary', SIBOEHM:'https://siboehm.com/articles/22/CUDA-MMM',
  SALYKOVA:'https://salykova.github.io/gemm-gpu', HORACE:'https://horace.io/brrr_intro.html',
  DAMEK:'https://damek.github.io/random/basic-facts-about-gpus/',
  HAMZA:'https://hamzaelshafie.bearblog.dev/worklog-optimising-gemm-on-nvidia-h100-for-cublas-like-performance-wip/',
  CUDAFORFUN:'https://cudaforfun.substack.com/p/outperforming-cublas-on-h100-a-worklog',
  ALEXARMBR:'https://alexarmbr.github.io/2024/08/10/How-To-Write-A-Fast-Matrix-Multiplication-From-Scratch-With-Tensor-Cores.html',
  KAPILSH:'https://kapilsh.github.io/posts/learn-cutlass-the-hard-way/', GPUPUZZLES:'https://github.com/srush/GPU-Puzzles',
  NVFP4:'https://yue-zhang-2025.github.io/2025/12/02/blackwell-nvfp4-kernel-hackathon-journey.html',
  VLLMDBG:'https://vllm.ai/blog/2025-12-03-improved-cuda-debugging', SIMONGUO:'https://simonguo.tech/blog/2025-10-automated-gpu-kernels.html',
  CRFM:'https://crfm.stanford.edu/2025/05/28/fast-kernels.html', DSPARK:'https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro-DSpark',
  CS149:'https://github.com/stanford-cs149/asst5-kernels', GPUMODE:'https://github.com/gpu-mode/lectures',
}

const ARTICLES = [
  {slug:'why-kernels-run-the-world', section:'00 Start Here', title:'Why kernels run the world', brief:'Motivational + framing: every frontier model bottoms out in hand-tuned kernels; the model->PyTorch->kernel->SASS stack; why this layer is scarce, high-leverage, and increasingly hireable; what the rest of the site delivers. Set stakes, be inspiring but concrete.', src:`${S.HORACE}, ${S.SIMONGUO}`},
  {slug:'speed-of-light-thinking', section:'00 Start Here', title:'Speed-of-light thinking & the roofline', brief:'Peak FLOP/s vs peak bytes/s, arithmetic intensity, the ridge point (~295 for H100 bf16), the roofline plot and how to read it, and estimating the fastest a kernel could run before writing it. Complements the three-regimes article.', src:`${S.HORACE}, ${S.DAMEK}`},
  {slug:'the-kernel-engineers-skill-map', section:'00 Start Here', title:'The kernel engineer skill map', brief:'The concrete skill checklist a kernel-eng hiring manager expects (matmul-from-scratch, tensor-core matmul, beating cuBLAS on H100, GPU MODE profiling->CUTLASS->SASS, CUTLASS the hard way, AI-generated kernels), and exactly where on this site each is taught (map to lectures/workshops/sections). End with the sentence a graduate can honestly say.', src:`${S.SIBOEHM}, ${S.ALEXARMBR}, ${S.CUDAFORFUN}, ${S.GPUMODE}, ${S.KAPILSH}, ${S.SIMONGUO}, ${S.CRFM}`},
  {slug:'how-to-use-this-site', section:'00 Start Here', title:'How to use this site', brief:'Meta/orientation: the two surfaces (terminal shell + paper worklog), the worklog method, the GPU-Puzzles async track, the live lectures vs the independent knowledge base, and a suggested reading order for beginners vs people who already know CUDA.', src:`${S.MODAL}`},
  {slug:'streaming-multiprocessor', section:'01 The GPU, From Silicon Up', title:'The Streaming Multiprocessor', brief:'The SM as the unit of GPU compute: 4 sub-partitions each with a warp scheduler, dispatch, register file slice, CUDA/tensor cores; the shared SMEM/L1; how blocks map to SMs; why the SM is where every occupancy/latency tradeoff plays out. H100 has ~132 SMs.', src:`${S.MODAL}, ${S.HAMZA}`},
  {slug:'cuda-cores', section:'01 The GPU, From Silicon Up', title:'CUDA cores & the FP32/INT pipes', brief:'The scalar ALUs (FP32/FP64/INT), FMA, why they are no longer where most FLOPs live (tensor cores dominate), and when CUDA cores still matter (elementwise, addressing, non-matmul math). Contrast throughput with tensor cores.', src:`${S.MODAL}, ${S.DAMEK}`},
  {slug:'tensor-cores', section:'01 The GPU, From Silicon Up', title:'Tensor cores', brief:'MMA engines doing D=A*B+C on small tiles; ~95% of H100 FLOPs; shapes (m16n8k16 etc), precisions (TF32/BF16/FP16/FP8), fragment/warp cooperation, why kernels are written AROUND them; preview of wmma/mma.sync/wgmma. 989 TF/s bf16.', src:`${S.MODAL}, ${S.ALEXARMBR}`},
  {slug:'warp-scheduler', section:'01 The GPU, From Silicon Up', title:'The warp scheduler & latency hiding', brief:'How the SM hides ~400-cycle global latency by switching among resident warps each cycle; issue slots; why you want many warps in flight; the direct link to occupancy; stall reasons you see in Nsight.', src:`${S.MODAL}, ${S.DAMEK}`},
  {slug:'register-file', section:'01 The GPU, From Silicon Up', title:'The register file', brief:'256 KB/SM (65536 32-bit registers), ~1-cycle latency, per-thread privacy with the warp-shuffle exception; register pressure vs occupancy tradeoff; max 255 regs/thread; spills to local memory (HBM) and why that hurts; ptxas allocates them.', src:`${S.HAMZA}, ${S.MODAL}`},
  {slug:'shared-memory-l1', section:'01 The GPU, From Silicon Up', title:'Shared memory & L1', brief:'Programmable on-chip scratchpad co-located with L1, ~228 KiB usable SMEM out of 256 KiB, 32 banks, ~31 TB/s; the key optimization surface (tiling); configurable SMEM/L1 split; preview bank conflicts. This is the star of the GEMM ladder.', src:`${S.HAMZA}, ${S.SIBOEHM}`},
  {slug:'l2-cache', section:'01 The GPU, From Silicon Up', title:'The L2 cache & partitions', brief:'~50 MiB, two partitions joined by a crossbar (near/far latency), 128 B line = 4x32 B sectors, data-compression circuitry + global atomics, residency control for persistent data, 32/64/128 B transaction granularity via cudaDeviceSetLimit.', src:`${S.HAMZA}, ${S.MODAL}`},
  {slug:'hbm-global-memory', section:'01 The GPU, From Silicon Up', title:'HBM, global memory & the package', brief:'Stacked DRAM dies + through-silicon vias + HBM controller die, silicon interposer, 1024 links/stack, ~3.35 TB/s, 80 GB; global vs local (spill) memory share the same DRAM; why every kernel is ultimately a memory-traffic problem. Draw the packaging stack.', src:`${S.HAMZA}, ${S.DAMEK}`},
  {slug:'gpc-tpc', section:'01 The GPU, From Silicon Up', title:'GPCs, TPCs & the chip floorplan', brief:'8 GPCs, ~18 SMs each on the die; N=144 on die but 132 (SXM5)/114 (PCIe) enabled because defective SMs are fused off; TPCs; thread-block clusters + distributed shared memory (Hopper) spanning SMs in a GPC.', src:`${S.HAMZA}, ${S.MODAL}`},
  {slug:'a100-h100-b200-whatchanged', section:'01 The GPU, From Silicon Up', title:'A100 to H100 to B200: what changed', brief:'The architectural deltas that each spawned new kernels: A100 (Ampere, cp.async, TF32), H100 (Hopper, TMA, wgmma, DSMEM, FP8, thread-block clusters), B200/GB300 (Blackwell, tcgen05, Tensor Memory TMEM, CTA pairs, NVFP4). Frame as each generation adds FLOPs faster than bandwidth (ridge point climbs).', src:`${S.HAMZA}, ${S.NVFP4}`},
  {slug:'roofline-model', section:'01 The GPU, From Silicon Up', title:'The roofline model in practice', brief:'The full roofline: memory-bandwidth roof (slope) + compute roof (flat), ridge point, plotting a real kernel, reading whether you are under the memory roof or the compute roof, and when to stop optimizing. Worked example with GEMM at several sizes.', src:`${S.HORACE}, ${S.DAMEK}`},
  {slug:'occupancy', section:'01 The GPU, From Silicon Up', title:'Occupancy: the balancing act', brief:'Occupancy = active warps / max warps; limited by registers/thread, SMEM/block, threads/block; the occupancy calculator logic; why higher occupancy hides latency but past a point costs registers/SMEM and is NOT always faster (low-occupancy high-ILP). Concrete numbers.', src:`${S.SIBOEHM}, ${S.MODAL}`},
  {slug:'arithmetic-intensity', section:'01 The GPU, From Silicon Up', title:'Arithmetic intensity', brief:'FLOPs per byte moved; how tiling/reuse raises it; the number that decides your regime; worked AI for GEMM (grows with N) vs elementwise (~0.5) vs the ridge point ~295; the target of every optimization on the GEMM ladder.', src:`${S.HORACE}, ${S.SIBOEHM}`},
  {slug:'memory-coalescing', section:'01 The GPU, From Silicon Up', title:'Memory coalescing', brief:'How a warp of 32 threads combines contiguous global loads into one 128 B (or 32 B sector) transaction; strided/misaligned access = many transactions = wasted bandwidth; the exact remap trick that fixes GEMM kernel 2; row-major layout implications.', src:`${S.SIBOEHM}, ${S.MODAL}`},
  {slug:'threads-warps-blocks-grids', section:'02 The CUDA Programming Model', title:'Threads, warps, blocks, grids', brief:'The execution hierarchy and its hardware mapping (thread->lane, warp=32->scheduler, block->SM, grid->GPU); blockIdx/threadIdx/blockDim indexing arithmetic; block size choices (multiples of 32); the 1024-thread limit; occupancy link.', src:`${S.MODAL}, ${S.DAMEK}`},
  {slug:'simt-and-divergence', section:'02 The CUDA Programming Model', title:'SIMT & warp divergence', brief:'32 threads share a program counter; how branches serialize (both sides masked) and halve throughput; independent thread scheduling (Volta+); avoiding divergence; the reconvergence intuition. Show an if/else diagram.', src:`${S.MODAL}`},
  {slug:'kernel-launch-anatomy', section:'02 The CUDA Programming Model', title:'Anatomy of a kernel launch', brief:'What the triple-angle-bracket launch (grid, block, smem, stream) does; launch latency (~few us) and why it makes tiny ops overhead-bound; grid/block dims; dynamic shared memory; how the driver queues the launch; CUDA graphs as the fix for launch overhead.', src:`${S.HORACE}, ${S.MODAL}`},
  {slug:'memory-spaces', section:'02 The CUDA Programming Model', title:'The memory spaces', brief:'Global, shared, local, constant, register, texture; latency/bandwidth/scope table; when to use each; local memory is really global (spills); constant cache broadcast; the mental map. Draw the pyramid.', src:`${S.HAMZA}, ${S.MODAL}`},
  {slug:'ptx-vs-sass', section:'02 The CUDA Programming Model', title:'PTX vs SASS: the compilation story', brief:'nvcc -> PTX (virtual ISA) -> ptxas -> SASS (native, per-arch); JIT vs AOT; why you read SASS (registers, instruction issue, LDG.E.128) to find the truth; cuobjdump/nvdisasm; the compilation-story sidebar. Include a tiny SASS snippet.', src:`${S.HAMZA}, ${S.MODAL}`},
  {slug:'compute-capability', section:'02 The CUDA Programming Model', title:'Compute capability & targeting', brief:'sm_XY, the -arch/-gencode flags, virtual vs real archs, why sm_90a (the a = architecture-specific, needed for wgmma/TMA on Hopper), forward compat via PTX JIT. Practical build guidance.', src:`${S.MODAL}, ${S.HAMZA}`},
  {slug:'bank-conflicts', section:'02 The CUDA Programming Model', title:'Shared-memory bank conflicts', brief:'32 banks x 4 B, the conflict rule (multiple lanes -> same bank, different word), n-way conflicts serialize; the padding (+1) fix and swizzling; worked example with a transpose/tile; how it shows up in the GEMM and tensor-core kernels.', src:`${S.SIBOEHM}, ${S.SALYKOVA}`},
  {slug:'atomics-and-reductions', section:'02 The CUDA Programming Model', title:'Atomics & reductions', brief:'Tree reduction in shared memory, warp-shuffle reduction (__shfl_down_sync), atomicAdd and contention, hierarchical block->global reduction; why naive atomics serialize; a correct fast sum kernel.', src:`${S.MODAL}, ${S.GPUPUZZLES}`},
  {slug:'streams-and-async', section:'02 The CUDA Programming Model', title:'Streams, events & async', brief:'CUDA streams for concurrency, overlapping copy+compute, events for timing/sync, cp.async (memcpy_async) to overlap GMEM->SMEM with compute (preview of double buffering), pinned memory. Draw a pipeline timeline.', src:`${S.SALYKOVA}, ${S.MODAL}`},
  {slug:'your-first-kernel', section:'02 The CUDA Programming Model', title:'Your first kernel, end to end', brief:'A complete worked first kernel: SAXPY then RGB->grayscale — launch config, boundary checks, host/device memory, and correct benchmarking (warmup, cudaEventRecord, repeat). The hello world that teaches the workflow. Full code.', src:`${S.GPUPUZZLES}, ${S.DAMEK}`},
  {slug:'gpu-puzzles-walkthrough-1', section:'02 The CUDA Programming Model', title:'GPU Puzzles, walkthrough I', brief:"Walk through the first ~6 of Sasha Rush GPU-Puzzles (map, zip, guard, broadcast, blocks, block-guard) — one-thread-one-element mental model, indexing, guards. Show the tiny solutions and the insight each teaches.", src:`${S.GPUPUZZLES}`},
  {slug:'gpu-puzzles-walkthrough-2', section:'02 The CUDA Programming Model', title:'GPU Puzzles, walkthrough II', brief:'Walk through the harder GPU-Puzzles (shared memory, pooling, dot product, 1D convolution, prefix sum, matmul) — where shared memory + cooperation + reductions enter. Bridge to the GEMM ladder.', src:`${S.GPUPUZZLES}`},
  {slug:'gemm-kernel-2-coalescing', section:'03 The GEMM Worklog', title:'Kernel 2: Global memory coalescing', brief:'The one-line thread-index remap so a warp reads contiguous columns -> coalesced GMEM access; profile shows fewer/fuller transactions; jumps naive 1.3% -> 8.5% of cuBLAS. Explain the remap carefully (it puzzles people). Continues from kernel 1.', src:`${S.SIBOEHM}`},
  {slug:'gemm-kernel-3-shared-memory', section:'03 The GEMM Worklog', title:'Kernel 3: Shared-memory tiling', brief:'Block over K; stage BMxBK and BKxBN tiles in SMEM, __syncthreads, accumulate across tiles; cuts GMEM traffic by tile width; 8.5% -> 12.8%. Why SMEM capacity forces blocking over K.', src:`${S.SIBOEHM}, ${S.SALYKOVA}`},
  {slug:'gemm-kernel-4-1d-blocktiling', section:'03 The GEMM Worklog', title:'Kernel 4: 1D block-tiling', brief:'Each thread computes TM outputs in a column, caching a column of As in registers and reusing a Bs value across TM results; raises arithmetic intensity; 12.8% -> 36.5%. The register-reuse idea.', src:`${S.SIBOEHM}`},
  {slug:'gemm-kernel-5-2d-blocktiling', section:'03 The GEMM Worklog', title:'Kernel 5: 2D block-tiling', brief:'Each thread computes a TMxTN register tile; loads TM+TN values, does TMxTN FMAs (reuse); the big jump 36.5% -> 68.7%. The outer-product accumulation per k. Show the per-thread register tile.', src:`${S.SIBOEHM}`},
  {slug:'gemm-kernel-6-vectorized', section:'03 The GEMM Worklog', title:'Kernel 6: Vectorized memory access', brief:'float4 / LDS.128 vectorized SMEM+GMEM loads, transposing As on load for vectorization; SASS shows 8 scalar loads -> 2 vector loads (the signature moment); 68.7% -> 78.4%. Include a SASS+diagram figure.', src:`${S.SIBOEHM}, ${S.HAMZA}`},
  {slug:'gemm-kernel-7-autotuning', section:'03 The GEMM Worklog', title:'Kernel 7: Autotuning the tiles', brief:'The parameter space (BM, BN, BK, TM, TN, blocktile, warps); grid-search/autotune per GPU rather than guess; occupancy vs tile-size tradeoffs; 78.4% -> 84.8%. The methodology of tuning.', src:`${S.SIBOEHM}`},
  {slug:'gemm-kernel-8-warptiling', section:'03 The GEMM Worklog', title:'Kernel 8: Warptiling', brief:'Add an explicit warp-tile level between block and thread (block->warp->thread), matching the warp-scheduler & register reuse; makes all parallelism explicit; 84.8% -> 93.7% (cuBLAS territory). The three-level tiling figure.', src:`${S.SIBOEHM}, ${S.HAMZA}`},
  {slug:'gemm-double-buffering-cpasync', section:'03 The GEMM Worklog', title:'Double buffering & cp.async', brief:'Prefetch the next K-tile into a second SMEM buffer with cp.async while computing on the current one, hiding GMEM latency; ping-pong buffers; the pipeline timeline. Where salykova and cuBLAS get their overlap.', src:`${S.SALYKOVA}, ${S.HAMZA}`},
  {slug:'gemm-cublas-baseline', section:'03 The GEMM Worklog', title:'What cuBLAS is actually doing', brief:'Demystify the black box we chase: shape heuristics, split-K, tensor-core paths, autotuned tile libraries, and why the last ~6% (94->100%) needs assembly-level tricks (CUTLASS/CuTe). Sets up the tensor-core and CUTLASS articles.', src:`${S.SIBOEHM}, ${S.KAPILSH}`},
  {slug:'gemm-benchmark-methodology', section:'03 The GEMM Worklog', title:'Benchmarking without lying to yourself', brief:'Warmup, locked clocks, L2 flush between runs, enough iterations, cudaEvent timing, computing TFLOP/s = 2*M*N*K/time, error vs a reference; the discipline that makes the whole ladder trustworthy. Common benchmarking mistakes.', src:`${S.SALYKOVA}, ${S.SIBOEHM}`},
  {slug:'gemm-recap-the-ladder', section:'03 The GEMM Worklog', title:'The ladder, end to end', brief:'Recap all kernels on one roofline + a %-of-cuBLAS table (1.3->8.5->12.8->36.5->68.7->78.4->84.8->93.7); the general principles that transfer to ANY kernel (coalesce, tile to SMEM, reuse in registers, vectorize, make parallelism explicit, autotune). A proper recap with the summary table.', src:`${S.SIBOEHM}`},
  {slug:'tc-kernel-1-wmma-intro', section:'03 The GEMM Worklog', title:'Tensor cores I: the WMMA GEMM', brief:'Rebuild matmul on tensor cores from scratch (after alexarmbr): the wmma API, load_matrix_sync fragments, the mma shape (e.g. m16n16k16), a first working tensor-core GEMM and its speed vs the SIMT best. Concept first, then code.', src:`${S.ALEXARMBR}, ${S.MODAL}`},
  {slug:'tc-kernel-2-fragments-swizzling', section:'03 The GEMM Worklog', title:'Tensor cores II: fragments & swizzling', brief:'Register-fragment layouts (who holds what), SMEM swizzling to avoid bank conflicts on the tensor-core load path, the profile proving the conflict is gone, and the speedup. The swizzle figure.', src:`${S.ALEXARMBR}, ${S.SALYKOVA}`},
  {slug:'tc-kernel-3-mma-sync-fast', section:'03 The GEMM Worklog', title:'Tensor cores III: to cuBLAS speed', brief:'Drop from wmma to mma.sync PTX, add double-buffered cp.async pipelines and the precision menu (TF32/BF16/FP16), reaching library-class tensor-core GEMM. Bridge to Hopper wgmma (section 05).', src:`${S.ALEXARMBR}, ${S.HAMZA}`},
  {slug:'prefill-vs-decode', section:'04 Kernels for Inference', title:'Prefill vs decode: two different machines', brief:'Prefill = big GEMMs (compute-bound), decode = one-token GEMV per step (memory-bound), why they need different kernels; the KV cache read dominates decode; batching helps decode. Frame with the three regimes.', src:`${S.HORACE}, ${S.DAMEK}`},
  {slug:'operator-fusion', section:'04 Kernels for Inference', title:'Operator fusion', brief:'The single highest-leverage inference optimization: stop round-tripping activations through HBM between elementwise ops; fused epilogues; why fusion is a memory-bandwidth win; examples (bias+GELU, RMSNorm+matmul). Draw the before/after HBM traffic.', src:`${S.HORACE}`},
  {slug:'softmax-from-scratch', section:'04 Kernels for Inference', title:'Softmax from scratch (and online)', brief:'Numerically-stable softmax (subtract max), the two-pass vs single-pass, the ONLINE softmax with running max+sum rescaling — the exact trick FlashAttention needs. Reduction kernel structure. Code + the rescale math.', src:`${S.HORACE}`},
  {slug:'rmsnorm-from-scratch', section:'04 Kernels for Inference', title:'RMSNorm & LayerNorm kernels', brief:'Reduction (mean/var or RMS) + normalize + affine fused into one pass; block-per-row layout, warp-shuffle reductions; why LayerNorm is a great AI-kernel benchmark (CRFM got 484%). Code.', src:`${S.HORACE}, ${S.CRFM}`},
  {slug:'attention-naive', section:'04 Kernels for Inference', title:'Attention, the naive way', brief:'QK^T -> softmax -> V as three separate kernels; the O(N^2) score matrix written to and read from HBM; why that memory traffic (not the FLOPs) is the bottleneck for long sequences; sets up FlashAttention.', src:`${S.HORACE}`},
  {slug:'flashattention-1', section:'04 Kernels for Inference', title:'FlashAttention I: tiling attention', brief:'Fuse the whole attention into one kernel using online softmax so the NxN scores never touch HBM; tile over Q/K/V blocks in SMEM, keep running max/sum/accumulator; the memory-traffic reduction. The tiling figure + rescale. Conceptual + kernel sketch.', src:`${S.HORACE}`},
  {slug:'flashattention-2', section:'04 Kernels for Inference', title:'FlashAttention II: better work partitioning', brief:'Reduce non-matmul work, parallelize over the sequence-length dim, better warp partitioning (fewer shared-memory syncs), causal-mask work skipping; ~2x over FA1. What changed and why.', src:`${S.HORACE}`},
  {slug:'flashattention-3', section:'04 Kernels for Inference', title:'FlashAttention III: Hopper & async', brief:'Use Hopper features: TMA async loads, wgmma, warp specialization (producer/consumer), FP8; overlap softmax with matmul (pingpong); attention near the hardware roofline. Links to section 05 Hopper articles.', src:`${S.HAMZA}, ${S.CUDAFORFUN}`},
  {slug:'kv-cache-and-paged-attention', section:'04 Kernels for Inference', title:'The KV cache & PagedAttention', brief:'Why decode is memory-bound (reads the whole KV cache per token); KV-cache layout; fragmentation; PagedAttention (block table, non-contiguous KV pages) and the kernel that gathers paged KV; FP8 KV cache. vLLM context.', src:`${S.VLLMDBG}, ${S.DSPARK}`},
  {slug:'quantization-kernels-fp8-int4', section:'04 Kernels for Inference', title:'Quantization kernels: FP8, INT4, W4A16', brief:'Dequantize-in-the-kernel, per-tensor/per-channel/group scales, W4A16 (4-bit weights, 16-bit acts) matmul, FP8 e4m3/e5m2, why low precision halves/quarters memory traffic (the real win) and the accuracy tradeoff. Kernel structure.', src:`${S.NVFP4}, ${S.DSPARK}`},
  {slug:'swiglu-kernel', section:'04 Kernels for Inference', title:'The SwiGLU kernel', brief:'gate = SiLU(x@Wg); out = (gate * (x@Wu)) @ Wd — fuse the SiLU + elementwise-multiply; a small fused kernel in every transformer MLP and a common KernelBench/CS149 target. Code + fusion figure.', src:`${S.CS149}, ${S.HORACE}`},
  {slug:'batched-decode-matvec', section:'04 Kernels for Inference', title:'Batched decode: the GEMV problem', brief:'Single-token decode = skinny matmul / GEMV (memory-bound); batching many sequences to reclaim arithmetic intensity; the tradeoff with latency; how tensor cores are underused here; continuous batching interplay.', src:`${S.HORACE}, ${S.DSPARK}`},
  {slug:'hopper-tma', section:'05 The Frontier', title:'Hopper TMA: async bulk copy', brief:'The Tensor Memory Accelerator: a hardware copy engine that moves multidimensional tiles GMEM<->SMEM with a single descriptor, freeing threads to compute; mbarriers for completion; how it replaces hand-rolled cp.async loops. sm_90a. Draw the descriptor+async copy.', src:`${S.HAMZA}, ${S.CUDAFORFUN}`},
  {slug:'hopper-wgmma-warp-specialization', section:'05 The Frontier', title:'WGMMA & warp specialization', brief:'Warpgroup MMA (wgmma.mma_async, m64nNk16) operating on 4 warps at once, async from SMEM; producer/consumer warp specialization (some warps TMA-load, others wgmma-compute) with mbarriers to keep tensor cores saturated. The pipeline.', src:`${S.HAMZA}, ${S.CUDAFORFUN}`},
  {slug:'beating-cublas-on-h100', section:'05 The Frontier', title:'Beating cuBLAS on an H100', brief:'A full worklog assembling TMA + wgmma + warp specialization + double buffering into a GEMM that matches/beats cuBLAS (kernel-7 in hamza; the cudaforfun worklog); the SASS/profile evidence; what the last few percent cost. This is the flagship section-05 worklog — be thorough, hypothesis->measure per step.', src:`${S.HAMZA}, ${S.CUDAFORFUN}`},
  {slug:'blackwell-tcgen05-tmem', section:'05 The Frontier', title:'Blackwell: tcgen05 & tensor memory', brief:'5th-gen tensor cores (tcgen05), the NEW Tensor Memory (TMEM) as an accumulator space distinct from registers/SMEM, CTA pairs cooperating on one MMA, and why kernels are restructured for it. B200/GB300. Draw the new memory in the hierarchy.', src:`${S.NVFP4}`},
  {slug:'nvfp4-microscaling', section:'05 The Frontier', title:'NVFP4 & microscaling formats', brief:'NVFP4 = e2m1 (4-bit) values with per-block FP8 (e4m3) scale factors (microscaling); the hackathon journey 2000us -> 22.3us FP4 GEMV: use FP4/FP8 decode intrinsics (443->39us) not bit-twiddling, ILP over tiles, PTX fusion; CuTe-DSL (100->33us) vs raw CUDA paths. Be specific with the journey numbers.', src:`${S.NVFP4}`},
  {slug:'deepseek-flashmla-deepgemm', section:'05 The Frontier', title:'DeepSeek open kernels: FlashMLA & DeepGEMM', brief:'FlashMLA = MLA (multi-head latent attention) decode kernel optimized for Hopper/paged KV; DeepGEMM = clean FP8 (and MoE) GEMM library, the deep_gemm_mega_moe backend; why an LLM lab ships its own kernels; how these plug into serving. Ground in the DSpark model card deployment notes.', src:`${S.DSPARK}`},
  {slug:'deepseek-dspark-speculative', section:'05 The Frontier', title:'DSpark: speculative decoding as a kernel problem', brief:'DeepSeek-V4-Pro-DSpark = the V4-Pro checkpoint (1.6T total / 49B activated, 1M context, FP4 experts + FP8, CSA/HCA sparse attention: 27% of V3.2 FLOPs at 1M ctx, 10% KV cache) PLUS a speculative-decoding module. Explain spec-dec as a KERNELS problem: draft forward passes, parallel verification, acceptance-sampling kernels, batching interplay, deep_gemm_mega_moe backend, GB300 nodes. Accurate to the model card.', src:`${S.DSPARK}`},
  {slug:'cutlass-the-hard-way', section:'05 The Frontier', title:'CUTLASS the hard way', brief:'From a naive GEMM up to a real CUTLASS kernel (after kapilsh): the CUTLASS hierarchy (device/kernel/threadblock/warp/mma), CuTe Layouts and Tensors, how library warptiling maps onto the vocabulary from our section-03 ladder; when to use CUTLASS vs hand-CUDA.', src:`${S.KAPILSH}`},
  {slug:'cute-dsl-tilelang', section:'05 The Frontier', title:'CuTe, the DSL landscape & Triton', brief:'CuTe layouts/tensors as the algebra behind CUTLASS; Triton (write a GEMM/softmax in ~40 lines, what the compiler does for you: coalescing/SMEM/pipelining, and what it cannot do); TileLang; when to drop to raw CUDA. Compare the abstraction levels.', src:`${S.KAPILSH}, ${S.CRFM}`},
  {slug:'debugging-kernels-vllm-workflow', section:'05 The Frontier', title:'Debugging kernels: the vLLM workflow', brief:'The real workflow: compute-sanitizer for races/OOB; hanging kernels (Ctrl-C useless) -> user-triggered core dumps via CUDA_ENABLE_USER_TRIGGERED_COREDUMP + named pipe; cuda-gdb on the dump; NVCC_PREPEND_FLAGS=-lineinfo to map SASS->source; nvdisasm -gi to see the full inline call stack; disable ccache. Follow the vLLM blog closely.', src:`${S.VLLMDBG}`},
  {slug:'kernelbench-and-fast-p', section:'06 AI x Kernels', title:'KernelBench & measuring AI kernels', brief:'KernelBench: transpile PyTorch -> CUDA, 3 levels (single op / fused sequence / full architecture like ViT/Mamba); the fast_p metric (% correct AND >=p x faster than PyTorch eager/compile); frontier models start <20%; why correct-and-fast is a hard multi-objective bar.', src:`${S.SIMONGUO}`},
  {slug:'test-time-scaling-and-search', section:'06 AI x Kernels', title:'Monkeys & search: test-time scaling', brief:'Test-time scaling: sampling many kernels (monkeys) — DeepSeek-V3 100 samples 4%->37% on Level 2, ->72% with iterative feedback; evolutionary/tree search (Sakana, Ouyang, AlphaEvolve) with an archive of good kernels; the propose->compile->profile->iterate loop as a search over programs.', src:`${S.SIMONGUO}, ${S.CRFM}`},
  {slug:'crfm-fast-kernels-experiments', section:'06 AI x Kernels', title:'The CRFM experiments', brief:'Stanford CRFM: natural-language optimization ideas first, then parallel branching implementations, best-seeds-next-round, 5 rounds with o3+Gemini-2.5-Pro; results: Conv2D 179.9%, Softmax 111.8%, LayerNorm 484.4%, fused Conv+ReLU+MaxPool 290% of PyTorch — AND the honest failures: FP16 matmul 52%, FlashAttention 9%. Discuss where it wins/fails and why (FP32 less-optimized workloads).', src:`${S.CRFM}`},
  {slug:'kevin-rl-and-kernelbook', section:'06 AI x Kernels', title:'Kevin, RL & what is still human', brief:'Multi-turn RL with verifiable rewards (correctness+speedup): Kevin took QwQ-32B 56%->82% correct, 0.53x->1.10x speedup, beating o1-mini; KernelBook (synthetic data from torch.compile Triton output) + KernelLLM-8B; GPU MODE 60k+ submissions; open problems (hardware-specific intrinsics, DSL scarcity 0.073% of corpora); conclusion: human+AI+profiler loop — a harness (cross-link the idea to agentic harnesses).', src:`${S.SIMONGUO}, ${S.GPUMODE}`},
]

phase('Write')
log(`Writing ${ARTICLES.length} articles across parallel agents, then verifying each…`)
const results = await pipeline(
  ARTICLES,
  a => agent(writePrompt(a), { label: `write:${a.slug}`, phase: 'Write' }).then(r => ({ a, write: r })),
  (prev, a) => agent(verifyPrompt(a), { label: `verify:${a.slug}`, phase: 'Verify' }).then(v => ({ slug: a.slug, verify: v })),
)
const ok = results.filter(Boolean)
log(`Done: ${ok.length}/${ARTICLES.length} articles written + verified.`)
return { total: ARTICLES.length, completed: ok.length, slugs: ok.map(r => r.slug) }
